"use strict";
// This file is auto-generated by @hey-api/openapi-ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.$ValidationError = exports.$UserCreate = exports.$User = exports.$ItemCreate = exports.$Item = exports.$HTTPValidationError = void 0;
exports.$HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
};
exports.$Item = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        owner_id: {
            type: 'integer',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'Item'
};
exports.$ItemCreate = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
};
exports.$User = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/Item'
            },
            type: 'array',
            title: 'Items',
            default: []
        }
    },
    type: 'object',
    required: ['email', 'id', 'is_active'],
    title: 'User'
};
exports.$UserCreate = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
};
exports.$ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
};
