// This file is auto-generated by @hey-api/openapi-ts

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $PatientCreate = {
    properties: {
        patient_doctor_id: {
            type: 'integer',
            title: 'Patient Doctor Id'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        identification_number: {
            type: 'string',
            title: 'Identification Number'
        },
        birthday: {
            type: 'string',
            format: 'date',
            title: 'Birthday'
        }
    },
    type: 'object',
    required: ['patient_doctor_id', 'first_name', 'last_name', 'email', 'identification_number', 'birthday'],
    title: 'PatientCreate'
} as const;

export const $PatientDto = {
    properties: {
        user_account_id: {
            type: 'integer',
            title: 'User Account Id'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        patient_doctor_id: {
            type: 'integer',
            title: 'Patient Doctor Id'
        },
        user_type_id: {
            type: 'integer',
            title: 'User Type Id'
        },
        identification_number: {
            type: 'string',
            title: 'Identification Number'
        }
    },
    type: 'object',
    required: ['user_account_id', 'first_name', 'last_name', 'patient_doctor_id', 'user_type_id', 'identification_number'],
    title: 'PatientDto'
} as const;

export const $PatientUpdate = {
    properties: {
        user_account_id: {
            type: 'integer',
            title: 'User Account Id'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        identification_number: {
            type: 'string',
            title: 'Identification Number'
        }
    },
    type: 'object',
    required: ['user_account_id', 'first_name', 'last_name', 'email', 'identification_number'],
    title: 'PatientUpdate'
} as const;

export const $PatientUpsertResponseDto = {
    properties: {
        user_account_id: {
            type: 'integer',
            title: 'User Account Id'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        patient_doctor_id: {
            type: 'integer',
            title: 'Patient Doctor Id'
        },
        user_type_id: {
            type: 'integer',
            title: 'User Type Id'
        },
        identification_number: {
            type: 'string',
            title: 'Identification Number'
        }
    },
    type: 'object',
    required: ['user_account_id', 'first_name', 'last_name', 'patient_doctor_id', 'user_type_id', 'identification_number'],
    title: 'PatientUpsertResponseDto'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;