// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { CreateUserData, CreateUserError, CreateUserResponse, ReadUsersData, ReadUsersError, ReadUsersResponse, ReadUserData, ReadUserError, ReadUserResponse, CreateItemForUserData, CreateItemForUserError, CreateItemForUserResponse, ReadItemsData, ReadItemsError, ReadItemsResponse, CreateItemData, CreateItemError, CreateItemResponse, RootError, RootResponse } from './types.gen';

export const client = createClient(createConfig());

export class UsersService {
    /**
     * Create User
     */
    public static createUser<ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateUserResponse, CreateUserError, ThrowOnError>({
            ...options,
            url: '/users/'
        });
    }
    
    /**
     * Read Users
     */
    public static readUsers<ThrowOnError extends boolean = false>(options?: Options<ReadUsersData, ThrowOnError>) {
        return (options?.client ?? client).get<ReadUsersResponse, ReadUsersError, ThrowOnError>({
            ...options,
            url: '/users/list'
        });
    }
    
    /**
     * Read User
     */
    public static readUser<ThrowOnError extends boolean = false>(options: Options<ReadUserData, ThrowOnError>) {
        return (options?.client ?? client).get<ReadUserResponse, ReadUserError, ThrowOnError>({
            ...options,
            url: '/users/{user_id}'
        });
    }
    
    /**
     * Create Item For User
     */
    public static createItemForUser<ThrowOnError extends boolean = false>(options: Options<CreateItemForUserData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateItemForUserResponse, CreateItemForUserError, ThrowOnError>({
            ...options,
            url: '/users/{user_id}/items/'
        });
    }
    
}

export class ItemsService {
    /**
     * Read Items
     */
    public static readItems<ThrowOnError extends boolean = false>(options?: Options<ReadItemsData, ThrowOnError>) {
        return (options?.client ?? client).get<ReadItemsResponse, ReadItemsError, ThrowOnError>({
            ...options,
            url: '/items/'
        });
    }
    
    /**
     * Create Item
     */
    public static createItem<ThrowOnError extends boolean = false>(options: Options<CreateItemData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateItemResponse, CreateItemError, ThrowOnError>({
            ...options,
            url: '/items/'
        });
    }
    
}

export class DefaultService {
    /**
     * Root
     */
    public static root<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<RootResponse, RootError, ThrowOnError>({
            ...options,
            url: '/'
        });
    }
    
}