"use strict";
// This file is auto-generated by @hey-api/openapi-ts
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.DefaultService = exports.ItemsService = exports.UsersService = exports.client = void 0;
var client_fetch_1 = require("@hey-api/client-fetch");
exports.client = (0, client_fetch_1.createClient)((0, client_fetch_1.createConfig)());
var UsersService = /** @class */ (function () {
    function UsersService() {
    }
    /**
     * Create User
     */
    UsersService.createUser = function (options) {
        var _a;
        return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).post(__assign(__assign({}, options), { url: '/users/' }));
    };
    /**
     * Read Users
     */
    UsersService.readUsers = function (options) {
        var _a;
        return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/users/list' }));
    };
    /**
     * Read User
     */
    UsersService.readUser = function (options) {
        var _a;
        return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/users/{user_id}' }));
    };
    /**
     * Create Item For User
     */
    UsersService.createItemForUser = function (options) {
        var _a;
        return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).post(__assign(__assign({}, options), { url: '/users/{user_id}/items/' }));
    };
    return UsersService;
}());
exports.UsersService = UsersService;
var ItemsService = /** @class */ (function () {
    function ItemsService() {
    }
    /**
     * Read Items
     */
    ItemsService.readItems = function (options) {
        var _a;
        return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/items/' }));
    };
    /**
     * Create Item
     */
    ItemsService.createItem = function (options) {
        var _a;
        return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).post(__assign(__assign({}, options), { url: '/items/' }));
    };
    return ItemsService;
}());
exports.ItemsService = ItemsService;
var DefaultService = /** @class */ (function () {
    function DefaultService() {
    }
    /**
     * Root
     */
    DefaultService.root = function (options) {
        var _a;
        return ((_a = options === null || options === void 0 ? void 0 : options.client) !== null && _a !== void 0 ? _a : exports.client).get(__assign(__assign({}, options), { url: '/' }));
    };
    return DefaultService;
}());
exports.DefaultService = DefaultService;
