// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { ListData, ListError, ListResponse, CreateData, CreateError, CreateResponse, UpdateData, UpdateError, UpdateResponse, RootError, RootResponse } from './types.gen';

export const client = createClient(createConfig());

export class PatientsService {
    /**
     * List
     */
    public static list<ThrowOnError extends boolean = false>(options?: Options<ListData, ThrowOnError>) {
        return (options?.client ?? client).get<ListResponse, ListError, ThrowOnError>({
            ...options,
            url: '/patient/list'
        });
    }
    
    /**
     * Create
     */
    public static create<ThrowOnError extends boolean = false>(options: Options<CreateData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateResponse, CreateError, ThrowOnError>({
            ...options,
            url: '/patient/create'
        });
    }
    
    /**
     * Update
     */
    public static update<ThrowOnError extends boolean = false>(options: Options<UpdateData, ThrowOnError>) {
        return (options?.client ?? client).put<UpdateResponse, UpdateError, ThrowOnError>({
            ...options,
            url: '/patient/update/{patient_id}'
        });
    }
    
}

export class DefaultService {
    /**
     * Root
     */
    public static root<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<RootResponse, RootError, ThrowOnError>({
            ...options,
            url: '/'
        });
    }
    
}