// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Item = {
    title: string;
    description?: (string | null);
    id: number;
    owner_id: number;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type User = {
    email: string;
    id: number;
    is_active: boolean;
    items?: Array<Item>;
};

export type UserCreate = {
    email: string;
    password: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CreateUserData = {
    body: UserCreate;
};

export type CreateUserResponse = (User);

export type CreateUserError = (unknown | HTTPValidationError);

export type ReadUsersData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ReadUsersResponse = (Array<User>);

export type ReadUsersError = (unknown | HTTPValidationError);

export type ReadUserData = {
    path: {
        user_id: number;
    };
};

export type ReadUserResponse = (User);

export type ReadUserError = (unknown | HTTPValidationError);

export type CreateItemForUserData = {
    body: ItemCreate;
    path: {
        user_id: number;
    };
};

export type CreateItemForUserResponse = (Item);

export type CreateItemForUserError = (unknown | HTTPValidationError);

export type ReadItemsData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ReadItemsResponse = (Array<Item>);

export type ReadItemsError = (unknown | HTTPValidationError);

export type CreateItemData = {
    body: ItemCreate;
};

export type CreateItemResponse = (ItemCreate);

export type CreateItemError = (unknown | HTTPValidationError);

export type RootResponse = (unknown);

export type RootError = unknown;