// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PatientCreate = {
    patient_doctor_id: number;
    first_name: string;
    last_name: string;
    email: string;
    identification_number: string;
    birthday: string;
};

export type PatientDto = {
    user_account_id: number;
    first_name: string;
    last_name: string;
    patient_doctor_id: number;
    user_type_id: number;
    identification_number: string;
};

export type PatientUpdate = {
    user_account_id: number;
    first_name: string;
    last_name: string;
    email: string;
    identification_number: string;
};

export type PatientUpsertResponseDto = {
    user_account_id: number;
    first_name: string;
    last_name: string;
    patient_doctor_id: number;
    user_type_id: number;
    identification_number: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ListData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ListResponse = (PatientDto);

export type ListError = (unknown | HTTPValidationError);

export type CreateData = {
    body: PatientCreate;
};

export type CreateResponse = (PatientUpsertResponseDto);

export type CreateError = (unknown | HTTPValidationError);

export type UpdateData = {
    body: PatientUpdate;
    path: {
        patient_id: number;
    };
};

export type UpdateResponse = (PatientUpsertResponseDto);

export type UpdateError = (unknown | HTTPValidationError);

export type RootResponse = (unknown);

export type RootError = unknown;